tree model created and backbone for adding tree completed
Learn-by-doing/hobobar pull request #52
Opened 2017-04-17 18:44 UTC by karliatto

- Tree model created
- Url for the collection added
- New backbone event to add new tree to the collection

When I try to add a new item to the collection I have the error message from the server ''' TypeError: Cannot read property 'latitude' of undefined ''' I am no sure if the server is ready to accept this post from backbone.

2017-04-18 11:53 UTC, chill117 requested changes
The "Add" button doesn't work for me. I am seeing the following error in the web server:
```
TypeError: Cannot read property 'latitude' of undefined
    at hobobar/server/controllers/api/tree/create.js:22:23
```

Is it working for you?

2017-04-18 11:53 UTC, chill117 commented on app/js/models/tree.js
> +Backbone.Model.prototype.idAttribute = 'id';
This overrides the idAttribute for **all** backbone models in the app. I think it's better to put this in the extend below:
```js
Backbone.Model.extend({
    idAttribute: 'id'
});
```

2017-04-19 21:19 UTC, karliatto commented
- I found out we didn't have any body-parser in the server, so I added with this PR and now it's working ok, req.body was undefined.
- filename is included in the body as well  since we do not have the camera in order to be able to test it.

2017-04-20 10:11 UTC, chill117 commented
I don't think this will work with an actual image upload anymore. It was working before [here](https://github.com/Learn-by-doing/hobobar/blob/25a6c754de2b1afeb21d2100d1ba2796ea69b4da/app/www/js/index.js#L18-L42).

It might be necessary to overwrite the tree model's `sync` method with our own custom method (with the code linked above).

2017-05-04 15:52 UTC, chill117 commented
@karliatto So what do we want to do with this? I think it's close.

2017-05-04 17:29 UTC, karliatto commented
@chill117 I think it's close as well
by the way I wanted to share with you that I did some research in debugging cordova apps and actually chrome or chromium has a functionality for that! you go to "chrome://inspect/#devices" connect the device and open the app in the device, and you can use developers tool as in a normal website, with the current status of this PR I get an error when the app tries to find  "Request URL:file:///android_asset/www/js/leaflet-src.map". does it tell you anything?

2017-05-05 14:25 UTC, chill117 commented
@karliatto Cool! I'll give that a try :)

2017-05-15 17:24 UTC, RobinCsl commented on app/index.html
> +            <label><input id="type" type="radio" name="type" value="tree">Tree</label>
The 3 inputs have the same id.

2017-05-17 10:25 UTC, chill117 commented on app/index.html
> +            <label><input id="type" type="radio" name="type" value="tree">Tree</label>
Could catch. I removed the duplicate IDs with a new commit.

2017-05-17 10:33 UTC, merged